spring.application.name=foodsharing-einab-tabelle-local
app.auth.booking-confirmation-validity-minutes=60
app.frontend.base-url=http://localhost:4200
app.mail.from=noreply@localhost
spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.foodsharing.token-encryption-key=${FOODSHARING_TOKEN_ENCRYPTION_KEY:fusOIjvTfaxR6t41gBicoXY3YkdWEKFmO4t3psGpuQ0=}

app.foodsharing.admin-user=${FOODSHARING_ADMIN_USER:ericz993@gmail.com}
app.foodsharing.admin-password=${FOODSHARING_ADMIN_PASSWORD:8636Eric1997}