/**
 * Foodsharing API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HelloResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HelloServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Return a hello message
     * 
*/
    getHello(extraHttpRequestParams?: any): Observable<HelloResponse>;

}
